/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://wgqah3ekrnfvranqzhgtqmgry4.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fz7rus26i5abnnjmgaconni7yy",
    "aws_cognito_identity_pool_id": "us-west-2:a240ea88-1508-463d-a16a-eb17dff9a7a2",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_e5E7Vn8rI",
    "aws_user_pools_web_client_id": "45dq3u623k26h2na9480udfpro",
    "oauth": {},
    "aws_user_files_s3_bucket": "pickone7e5c64f4dac44c8c8e125920b8ca2cb2123600-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
